# Print a new line before the prompt
add_newline = false

# [line_break]
# disabled = true
[battery]
format = "[B $percentage]($style) "
[[battery.display]]
threshold = 9

[character]      # The name of the module we are configuring is "character"
success_symbol = "[â†˜](bold green)"
error_symbol = "[â†˜](bold red)"
vicmd_symbol = "[â†™ï¸](bold green)"

[git_branch]
truncation_length = 20
truncation_symbol = "â€¦"

[git_commit]
style = "white"
commit_hash_length = 7
only_detached = false
format = "[$hash]($style) "

[git_status]
deleted = 'd'
modified = 'm'
untracked = '?'
# stashed = 's'

[package]
# symbol = "ğŸ "

[nodejs]
symbol = "n "
disabled = true

[directory]
truncation_length = 4
truncate_to_repo = true
